version: "3.9"
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    networks:
      mtignetwork:
          aliases:
             - c_influxdb
    volumes:
      - "v_influxdb:/var/lib/influxdb"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - "v_grafana:/var/lib/grafana"
    networks:
      - mtignetwork
    restart: unless-stopped
    
  mosquitto:
    image: eclipse-mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    networks:
      mtignetwork:
          aliases:
             -c_mosquitto
    restart: unless_stopped
    
  telegraf:
    image: telegraf
    networks:
      - mtignetwork
    restart: unless-stopped
    volumes:
      - "$(pwd):/conf/telegrafmqtt.conf:/etc/telegraf/telegraf.conf:ro"

volumes:
  v_influxdb:
  v_grafana:

networks:
  # The presence of these objects is sufficient to define them
  mtignetwork: {}